### ISSUE TITLE
Doesn't start in Mojave

### ISSUE THREAD

**Issue by Headmast** [xndrs/XSimulatorMngr#4]
After success build, `Unable to load Info.plist exceptions (eGPUOverrides)` is printed in a console.
There is the same [problem](https://stackoverflow.com/questions/52507950/unable-to-load-info-plist-error-xcode-10-under-macos-10-14-mojave).

**Comment by Intengine** [comment]
Same here. Projects are building, but nothing shows up. Seems like there is a problem with Mojave itself. You should downgrade the Xcode.

**Comment by xndrs** [comment]
It's a strange situation. First time when project builds and starts on Mojave it takes a time to start. Restart the app leads to good work.... 
Someone can reproduce this or it happens every time?

A warning about "Unable to load Info.plist" occurs even when run an empty macOS project (XCode 10, Mojave)
